### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by jxyk2007** [wordweb/Get-Tencent-Video-Live-Barrage-Gifts#1]
已扫码请在手机上点击确认登录！
已成功登录！
Traceback (most recent call last):
  File "A:\020-直播\视频号\Get-Tencent-Video-Live-Barrage-Gifts\webapi.py", line 953, in <module>
    if request_qrcode(retoken) and auth_data() and helper_upload_params() and  check_live_status() and get_live_info() and join_live() and a_online_member():
                                                                               ^^^^^^^^^^^^^^^^^^^
  File "A:\020-直播\视频号\Get-Tencent-Video-Live-Barrage-Gifts\webapi.py", line 434, in check_live_status
    live_description=rejson['data']['description']
                     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'description'

**Comment by jxyk2007** [comment]
要先开启直播，才能获取到直播id
